import type {
  GlossaryGender,
  GlossarySuggestion,
  GlossaryTerm,
  TermType,
} from '../../../shared/types'
import { generateId, getDatabase } from '../index'

// ============================================================================
// Glossary Term CRUD
// ============================================================================

/**
 * Create a new glossary term
 */
export function createGlossaryTerm(
  term: Omit<GlossaryTerm, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>
): GlossaryTerm {
  const db = getDatabase()
  const id = generateId()
  const now = new Date().toISOString()

  const stmt = db.prepare(`
    INSERT INTO glossary_terms (
      id, project_id, source_term, target_term, term_type, gender, pronouns,
      aliases_json, context, notes, auto_generated, confidence, source_context,
      usage_count, created_at, updated_at
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
  `)

  stmt.run(
    id,
    term.projectId,
    term.sourceTerm,
    term.targetTerm,
    term.termType,
    term.gender || null,
    term.pronouns || null,
    JSON.stringify(term.aliases || []),
    term.context || null,
    term.notes || null,
    term.autoGenerated ? 1 : 0,
    term.confidence,
    term.sourceContext || null,
    now,
    now
  )

  return {
    id,
    ...term,
    aliases: term.aliases || [],
    usageCount: 0,
    createdAt: now,
    updatedAt: now,
  }
}

/**
 * Get a glossary term by ID
 */
export function getGlossaryTerm(id: string): GlossaryTerm | null {
  const db = getDatabase()
  const stmt = db.prepare(`
    SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
           aliases_json, context, notes, auto_generated, confidence, source_context,
           usage_count, created_at, updated_at
    FROM glossary_terms
    WHERE id = ?
  `)

  const row = stmt.get(id) as GlossaryTermRow | undefined
  return row ? rowToGlossaryTerm(row) : null
}

/**
 * Get all glossary terms for a project (including global terms)
 */
export function listGlossaryTerms(projectId: string | null): GlossaryTerm[] {
  const db = getDatabase()

  let stmt
  if (projectId) {
    // Get project-specific terms and global terms
    stmt = db.prepare(`
      SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
             aliases_json, context, notes, auto_generated, confidence, source_context,
             usage_count, created_at, updated_at
      FROM glossary_terms
      WHERE project_id = ? OR project_id IS NULL
      ORDER BY source_term ASC
    `)
    return (stmt.all(projectId) as GlossaryTermRow[]).map(rowToGlossaryTerm)
  } else {
    // Get only global terms
    stmt = db.prepare(`
      SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
             aliases_json, context, notes, auto_generated, confidence, source_context,
             usage_count, created_at, updated_at
      FROM glossary_terms
      WHERE project_id IS NULL
      ORDER BY source_term ASC
    `)
    return (stmt.all() as GlossaryTermRow[]).map(rowToGlossaryTerm)
  }
}

/**
 * Search glossary terms
 */
export function searchGlossaryTerms(
  query: string,
  projectId?: string,
  termType?: TermType
): GlossaryTerm[] {
  const db = getDatabase()
  const searchPattern = `%${query}%`

  let sql = `
    SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
           aliases_json, context, notes, auto_generated, confidence, source_context,
           usage_count, created_at, updated_at
    FROM glossary_terms
    WHERE (source_term LIKE ? OR target_term LIKE ? OR aliases_json LIKE ?)
  `
  const params: unknown[] = [searchPattern, searchPattern, searchPattern]

  if (projectId) {
    sql += ' AND (project_id = ? OR project_id IS NULL)'
    params.push(projectId)
  }

  if (termType) {
    sql += ' AND term_type = ?'
    params.push(termType)
  }

  sql += ' ORDER BY usage_count DESC, source_term ASC'

  const rows = db.prepare(sql).all(...params) as GlossaryTermRow[]
  return rows.map(rowToGlossaryTerm)
}

/**
 * Update a glossary term
 */
export function updateGlossaryTerm(
  id: string,
  updates: Partial<Omit<GlossaryTerm, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>>
): void {
  const db = getDatabase()
  const now = new Date().toISOString()

  const setClauses: string[] = ['updated_at = ?']
  const values: unknown[] = [now]

  if (updates.projectId !== undefined) {
    setClauses.push('project_id = ?')
    values.push(updates.projectId)
  }
  if (updates.sourceTerm !== undefined) {
    setClauses.push('source_term = ?')
    values.push(updates.sourceTerm)
  }
  if (updates.targetTerm !== undefined) {
    setClauses.push('target_term = ?')
    values.push(updates.targetTerm)
  }
  if (updates.termType !== undefined) {
    setClauses.push('term_type = ?')
    values.push(updates.termType)
  }
  if (updates.gender !== undefined) {
    setClauses.push('gender = ?')
    values.push(updates.gender || null)
  }
  if (updates.pronouns !== undefined) {
    setClauses.push('pronouns = ?')
    values.push(updates.pronouns || null)
  }
  if (updates.aliases !== undefined) {
    setClauses.push('aliases_json = ?')
    values.push(JSON.stringify(updates.aliases))
  }
  if (updates.context !== undefined) {
    setClauses.push('context = ?')
    values.push(updates.context || null)
  }
  if (updates.notes !== undefined) {
    setClauses.push('notes = ?')
    values.push(updates.notes || null)
  }
  if (updates.confidence !== undefined) {
    setClauses.push('confidence = ?')
    values.push(updates.confidence)
  }

  values.push(id)
  const stmt = db.prepare(`UPDATE glossary_terms SET ${setClauses.join(', ')} WHERE id = ?`)
  stmt.run(...values)
}

/**
 * Delete a glossary term
 */
export function deleteGlossaryTerm(id: string): void {
  const db = getDatabase()
  db.prepare('DELETE FROM glossary_terms WHERE id = ?').run(id)
}

/**
 * Increment usage count for terms
 */
export function incrementTermUsage(termIds: string[]): void {
  if (termIds.length === 0) return
  const db = getDatabase()
  const placeholders = termIds.map(() => '?').join(', ')
  db.prepare(
    `UPDATE glossary_terms SET usage_count = usage_count + 1 WHERE id IN (${placeholders})`
  ).run(...termIds)
}

/**
 * Find a term by source text (exact match)
 */
export function findTermBySource(sourceTerm: string, projectId?: string): GlossaryTerm | null {
  const db = getDatabase()

  let stmt
  if (projectId) {
    stmt = db.prepare(`
      SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
             aliases_json, context, notes, auto_generated, confidence, source_context,
             usage_count, created_at, updated_at
      FROM glossary_terms
      WHERE source_term = ? AND (project_id = ? OR project_id IS NULL)
      ORDER BY project_id DESC
      LIMIT 1
    `)
    const row = stmt.get(sourceTerm, projectId) as GlossaryTermRow | undefined
    return row ? rowToGlossaryTerm(row) : null
  } else {
    stmt = db.prepare(`
      SELECT id, project_id, source_term, target_term, term_type, gender, pronouns,
             aliases_json, context, notes, auto_generated, confidence, source_context,
             usage_count, created_at, updated_at
      FROM glossary_terms
      WHERE source_term = ? AND project_id IS NULL
      LIMIT 1
    `)
    const row = stmt.get(sourceTerm) as GlossaryTermRow | undefined
    return row ? rowToGlossaryTerm(row) : null
  }
}

// ============================================================================
// Glossary Suggestions CRUD
// ============================================================================

/**
 * Create a glossary suggestion
 */
export function createGlossarySuggestion(
  suggestion: Omit<GlossarySuggestion, 'id' | 'status' | 'reviewedAt' | 'createdAt'>
): GlossarySuggestion {
  const db = getDatabase()
  const id = generateId()
  const now = new Date().toISOString()

  const stmt = db.prepare(`
    INSERT INTO glossary_suggestions (
      id, project_id, chapter_id, source_term, suggested_target, term_type,
      gender, confidence, source_context, status, reviewed_at, created_at
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', NULL, ?)
  `)

  stmt.run(
    id,
    suggestion.projectId,
    suggestion.chapterId || null,
    suggestion.sourceTerm,
    suggestion.suggestedTarget,
    suggestion.termType,
    suggestion.gender || null,
    suggestion.confidence,
    suggestion.sourceContext,
    now
  )

  return {
    id,
    ...suggestion,
    status: 'pending',
    createdAt: now,
  }
}

/**
 * Get pending suggestions for a project
 */
export function getPendingSuggestions(projectId: string): GlossarySuggestion[] {
  const db = getDatabase()
  const stmt = db.prepare(`
    SELECT id, project_id, chapter_id, source_term, suggested_target, term_type,
           gender, confidence, source_context, status, reviewed_at, created_at
    FROM glossary_suggestions
    WHERE project_id = ? AND status = 'pending'
    ORDER BY confidence DESC, created_at ASC
  `)

  const rows = stmt.all(projectId) as SuggestionRow[]
  return rows.map(rowToSuggestion)
}

/**
 * Accept a suggestion (creates a glossary term)
 */
export function acceptSuggestion(id: string): GlossaryTerm {
  const db = getDatabase()
  const suggestion = getSuggestion(id)

  if (!suggestion) {
    throw new Error(`Suggestion not found: ${id}`)
  }

  const now = new Date().toISOString()

  // Update suggestion status
  db.prepare(`
    UPDATE glossary_suggestions 
    SET status = 'accepted', reviewed_at = ?
    WHERE id = ?
  `).run(now, id)

  // Create the glossary term
  return createGlossaryTerm({
    projectId: suggestion.projectId,
    sourceTerm: suggestion.sourceTerm,
    targetTerm: suggestion.suggestedTarget,
    termType: suggestion.termType,
    gender: suggestion.gender,
    aliases: [],
    autoGenerated: true,
    confidence: suggestion.confidence,
    sourceContext: suggestion.sourceContext,
  })
}

/**
 * Reject a suggestion
 */
export function rejectSuggestion(id: string): void {
  const db = getDatabase()
  const now = new Date().toISOString()

  db.prepare(`
    UPDATE glossary_suggestions 
    SET status = 'rejected', reviewed_at = ?
    WHERE id = ?
  `).run(now, id)
}

/**
 * Merge a suggestion with an existing term
 */
export function mergeSuggestion(id: string, existingTermId: string): void {
  const db = getDatabase()
  const suggestion = getSuggestion(id)
  const existingTerm = getGlossaryTerm(existingTermId)

  if (!suggestion || !existingTerm) {
    throw new Error('Suggestion or existing term not found')
  }

  const now = new Date().toISOString()

  // Add the suggested translation as an alias if different
  if (suggestion.suggestedTarget !== existingTerm.targetTerm) {
    const aliases = [...existingTerm.aliases]
    if (!aliases.includes(suggestion.suggestedTarget)) {
      aliases.push(suggestion.suggestedTarget)
    }
    updateGlossaryTerm(existingTermId, { aliases })
  }

  // Update suggestion status
  db.prepare(`
    UPDATE glossary_suggestions 
    SET status = 'merged', reviewed_at = ?
    WHERE id = ?
  `).run(now, id)
}

/**
 * Get a specific suggestion
 */
export function getSuggestion(id: string): GlossarySuggestion | null {
  const db = getDatabase()
  const stmt = db.prepare(`
    SELECT id, project_id, chapter_id, source_term, suggested_target, term_type,
           gender, confidence, source_context, status, reviewed_at, created_at
    FROM glossary_suggestions
    WHERE id = ?
  `)

  const row = stmt.get(id) as SuggestionRow | undefined
  return row ? rowToSuggestion(row) : null
}

/**
 * Delete old rejected suggestions
 */
export function cleanupRejectedSuggestions(olderThanDays = 30): number {
  const db = getDatabase()
  const cutoff = new Date()
  cutoff.setDate(cutoff.getDate() - olderThanDays)

  const result = db
    .prepare(`
    DELETE FROM glossary_suggestions 
    WHERE status = 'rejected' AND reviewed_at < ?
  `)
    .run(cutoff.toISOString())

  return result.changes
}

// ============================================================================
// Bulk Operations
// ============================================================================

/**
 * Import glossary terms from an array
 */
export function importGlossaryTerms(
  terms: Array<Omit<GlossaryTerm, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>>,
  skipDuplicates = true
): { imported: number; skipped: number } {
  const db = getDatabase()
  let imported = 0
  let skipped = 0

  const transaction = db.transaction(() => {
    for (const term of terms) {
      if (skipDuplicates) {
        const existing = findTermBySource(term.sourceTerm, term.projectId || undefined)
        if (existing) {
          skipped++
          continue
        }
      }

      createGlossaryTerm(term)
      imported++
    }
  })

  transaction()
  return { imported, skipped }
}

/**
 * Export glossary terms for a project
 */
export function exportGlossaryTerms(projectId?: string): GlossaryTerm[] {
  return listGlossaryTerms(projectId || null)
}

// ============================================================================
// Internal helpers
// ============================================================================

interface GlossaryTermRow {
  id: string
  project_id: string | null
  source_term: string
  target_term: string
  term_type: string
  gender: string | null
  pronouns: string | null
  aliases_json: string
  context: string | null
  notes: string | null
  auto_generated: number
  confidence: number
  source_context: string | null
  usage_count: number
  created_at: string
  updated_at: string
}

interface SuggestionRow {
  id: string
  project_id: string
  chapter_id: string | null
  source_term: string
  suggested_target: string
  term_type: string
  gender: string | null
  confidence: number
  source_context: string
  status: string
  reviewed_at: string | null
  created_at: string
}

function rowToGlossaryTerm(row: GlossaryTermRow): GlossaryTerm {
  return {
    id: row.id,
    projectId: row.project_id,
    sourceTerm: row.source_term,
    targetTerm: row.target_term,
    termType: row.term_type as TermType,
    gender: (row.gender as GlossaryGender) || undefined,
    pronouns: row.pronouns || undefined,
    aliases: JSON.parse(row.aliases_json),
    context: row.context || undefined,
    notes: row.notes || undefined,
    autoGenerated: row.auto_generated === 1,
    confidence: row.confidence,
    sourceContext: row.source_context || undefined,
    usageCount: row.usage_count,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

function rowToSuggestion(row: SuggestionRow): GlossarySuggestion {
  return {
    id: row.id,
    projectId: row.project_id,
    chapterId: row.chapter_id || undefined,
    sourceTerm: row.source_term,
    suggestedTarget: row.suggested_target,
    termType: row.term_type as TermType,
    gender: (row.gender as GlossaryGender) || undefined,
    confidence: row.confidence,
    sourceContext: row.source_context,
    status: row.status as 'pending' | 'accepted' | 'rejected' | 'merged',
    reviewedAt: row.reviewed_at || undefined,
    createdAt: row.created_at,
  }
}
